first version of policy descriptor
sonata-nfv/tng-schema pull request #19
Opened 2018-02-08 13:51 UTC by efotopoulou

2018-02-08 14:34 UTC, mpeuster commented
I suggest to add a test to automatically validate the policy example against the policy schema.

Like done here:
- https://github.com/sonata-nfv/tng-schema/blob/master/package-specification/test/test_5gtango-ns-package-example.sh
- https://github.com/sonata-nfv/tng-schema/blob/master/service-descriptor/test/test_simplest-example.sh

2018-02-08 14:36 UTC, mpeuster reviewed
Schema as such looks fine to me.

2018-02-08 14:36 UTC, mpeuster requested changes
I suggest to add a test to automatically validate the policy example against the policy schema.

Like done here:
- https://github.com/sonata-nfv/tng-schema/blob/master/package-specification/test/test_5gtango-ns-package-example.sh
- https://github.com/sonata-nfv/tng-schema/blob/master/service-descriptor/test/test_simplest-example.sh

2018-02-08 14:37 UTC, StefanUPB commented on policy-descriptor/examples/policy-example.yml
> +# do NOT delete: this is used by tng-sdk-descriptorgen
you can delete these two comments as they only apply to the default VNFD and NSD at the moment

2018-02-08 14:44 UTC, stefanbschneider requested changes
Nice work :) But I suggest, you add tests and make sure the descriptor matches the defined schema.
You can check the other descriptors to see how the tests are structured and of course, I'm happy to help.

2018-02-08 14:44 UTC, StefanUPB commented on policy-descriptor/policy-schema.yml
> +         - $ref: "#/definitions/memory_units"
I guess, you need to include these definitions at the top too in order to reference them

2018-02-08 14:44 UTC, StefanUPB commented on policy-descriptor/examples/policy-example.yml
> +    action: "to be defined"
In the schema, you define action to be an array of objects with mandatory `type` field. I guess, you should set up tests (as Manuel suggested) in order to ensure the descriptors match the schema (and vice versa).

2018-02-08 14:44 UTC, StefanUPB commented on policy-descriptor/examples/policy-example.yml
> +# default YAML description of an ubuntu vm
you can delete these two comments as they only apply to the default VNFD and NSD at the moment

2018-02-24 09:13 UTC, mpeuster commented on policy-descriptor/examples/.~lock.policy-example.yml#
> +,eleni,elenipc.home,23.02.2018 15:45,file:///home/eleni/.config/libreoffice/4;
this is a temporary local file that should be removed from the PR.

2018-02-28 11:20 UTC, StefanUPB commented
Thanks for adding the tests. Now just remove the local files:
https://github.com/ubitech/tng-schema/blob/master/policy-descriptor/examples/.directory
https://github.com/ubitech/tng-schema/blob/master/policy-descriptor/examples/.%7Elock.policy-example.yml%23
Then the PR is ready to merge :)

2018-03-06 07:31 UTC, stefanbschneider approved these changes

2018-03-06 07:32 UTC, mpeuster approved these changes

2018-03-06 07:32 UTC, merged